# Generated by Django 4.0.3 on 2022-04-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_login_lid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': False},
        ),
    ]
