# Generated by Django 4.0.3 on 2022-04-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_login_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookedspc',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.IntegerField(db_column='sid')),
                ('email', models.CharField(db_column='email', max_length=50)),
            ],
            options={
                'db_table': 'bookedspc',
                'managed': False,
            },
        ),
    ]
